version: "3"

services:
  api:
    restart: always
    build: ./
    ports:
      - "5000:5000"
    env_file: ./.env
    networks:
      - metromo_network
    links:
      - "postgresdb:db"

  postgresdb:
    restart: always
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - metromo_network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=metromo
    volumes:
      - dbdata:/var/lib/postgresql/data/

volumes:
  dbdata:

networks:
  metromo_network:
    driver: bridge